/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.pkg2;

/**
 *
 * @author Luis B
 */
public class Ejercicio8 {
   private String dia="";
   private int diaActual=1,nuevodia=1,acum=diaActual;
   public String gdia1(String diaS,int d){
    if(d>31){
    return "Ese dia no existe";
    }
       if(("Domingo".equals(diaS))||("domingo".equals(diaS))){
       dia=diaS;
           diaActual=1; 
           while(acum<=d){
               if(diaActual==2){
                   dia="Lunes";
               }if(diaActual==3){
                   dia="Martes";
               }if(diaActual==4){
                   dia="Miercoles";
               }if(diaActual==5){
                   dia="Jueves";
               }if(diaActual==6){
                   dia="Viernes";
               }if(diaActual==7){
                   dia="Sabado";
               }if(diaActual==1){
                   dia="Domingo";
               }
               diaActual++;
               acum++;
               if(diaActual>7){
                   diaActual=1;
               }
           }
       }if(("Lunes".equals(diaS))||("lunes".equals(diaS))){
         dia=diaS;
           diaActual=1;
            while(acum<=d){
               if(diaActual==2){
                   dia="Martes";
               }if(diaActual==3){
                   dia="Miercoles";
               }if(diaActual==4){
                   dia="Jueves";
               }if(diaActual==5){
                   dia="Viernes";
               }if(diaActual==6){
                   dia="Sabado";
               }if(diaActual==7){
                   dia="Domingo";
               }if(diaActual==1){
                   dia="Lunes";
               }
               diaActual++;
               acum++;
               if(diaActual>7){
                   diaActual=1;
               }
            }
       }if(("Martes".equals(diaS))||("martes".equals(diaS))){
          dia=diaS;
           diaActual=1;
            while(acum<=d){
               if(diaActual==2){
                   dia="Miercoles";
               }if(diaActual==3){
                   dia="Jueves";
               }if(diaActual==4){
                   dia="Viernes";
               }if(diaActual==5){
                   dia="Sabado";
               }if(diaActual==6){
                   dia="Domingo";
               }if(diaActual==7){
                   dia="Lunes";
               }if(diaActual==1){
                   dia="Martes";
               }
               diaActual++;
               acum++;
               if(diaActual>7){
                   diaActual=1;
               }
            }
       }if(("Miercoles".equals(diaS))||("miercoles".equals(diaS))){
          dia=diaS;
           diaActual=1; 
            while(acum<=d){
               if(diaActual==2){
                   dia="Jueves";
               }if(diaActual==3){
                   dia="Viernes";
               }if(diaActual==4){
                   dia="Sabado";
               }if(diaActual==5){
                   dia="Domingo";
               }if(diaActual==6){
                   dia="Lunes";
               }if(diaActual==7){
                   dia="Martes";
               }if(diaActual==1){
                   dia="Miercoles";
               }
               diaActual++;
               acum++;
               if(diaActual>7){
                   diaActual=1;
               }
            }
       }if(("Jueves".equals(diaS))||("jueves".equals(diaS))){
          dia=diaS;
           diaActual=1; 
            while(acum<=d){
               if(diaActual==2){
                   dia="Viernes";
               }if(diaActual==3){
                   dia="Sabado";
               }if(diaActual==4){
                   dia="domingo";
               }if(diaActual==5){
                   dia="Lunes";
               }if(diaActual==6){
                   dia="Martes";
               }if(diaActual==7){
                   dia="Miercoles";
               }if(diaActual==1){
                   dia="Jueves";
               }
               diaActual++;
               acum++;
               if(diaActual>7){
                   diaActual=1;
               }
            }
       }if(("Viernes".equals(diaS))||("viernes".equals(diaS))){
          dia=diaS;
           diaActual=1;
            while(acum<=d){
               if(diaActual==2){
                   dia="Sabado";
               }if(diaActual==3){
                   dia="Domingo";
               }if(diaActual==4){
                   dia="Lunes";
               }if(diaActual==5){
                   dia="Martes";
               }if(diaActual==6){
                   dia="Miercoles";
               }if(diaActual==7){
                   dia="Jueves";
               }if(diaActual==1){
                   dia="Viernes";
               }
               diaActual++;
               acum++;
               if(diaActual>7){
                   diaActual=1;
               }
            }
       }if(("Sabado".equals(diaS))||("sabado".equals(diaS))){
          dia=diaS;
           diaActual=1; 
            while(acum<=d){
               if(diaActual==2){
                   dia="Domingo";
               }if(diaActual==3){
                   dia="Lunes";
               }if(diaActual==4){
                   dia="Martes";
               }if(diaActual==5){
                   dia="Miercoles";
               }if(diaActual==6){
                   dia="Jueves";
               }if(diaActual==7){
                   dia="Viernes";
               }if(diaActual==1){
                   dia="Sabado";
               }
               diaActual++;
               acum++;
               if(diaActual>7){
                   diaActual=1;
               }
            }
       }
    return dia;
   }
   }
