/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Luis B
 */
public class FrmGraficos extends javax.swing.JFrame {
 boolean esValido=false;
    /**
     * Creates new form FrmGraficos
     */
    public FrmGraficos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblPartido1 = new javax.swing.JLabel();
        lblPartido2 = new javax.swing.JLabel();
        lblpartido3 = new javax.swing.JLabel();
        txtPartido1 = new javax.swing.JTextField();
        txtPartido2 = new javax.swing.JTextField();
        txtPartido3 = new javax.swing.JTextField();
        btnGraficos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblPartido1.setText("Partido1");

        lblPartido2.setText("Partido2");

        lblpartido3.setText("Partido3");

        txtPartido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartido2ActionPerformed(evt);
            }
        });

        txtPartido3.setText(" ");
        txtPartido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartido3ActionPerformed(evt);
            }
        });

        btnGraficos.setText("Graficos");
        btnGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblpartido3)
                                .addGap(18, 18, 18)
                                .addComponent(txtPartido3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPartido2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPartido2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblPartido1)
                                .addGap(18, 18, 18)
                                .addComponent(txtPartido1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnGraficos)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPartido1)
                    .addComponent(txtPartido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPartido2)
                    .addComponent(txtPartido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpartido3)
                    .addComponent(txtPartido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnGraficos)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPartido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartido3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartido3ActionPerformed

    private void txtPartido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartido2ActionPerformed

    private void btnGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficosActionPerformed
        esValido=true;
        repaint();
        
    }//GEN-LAST:event_btnGraficosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGraficos().setVisible(true);
            }
        });
    }
    public void paint(Graphics g){
        super.paint(g);
    if(esValido){
        int valor1=Integer.parseInt(txtPartido1.getText());
        int valor2=Integer.parseInt(txtPartido2.getText());
        int valor3=Integer.parseInt(txtPartido3.getText());
        int suma=valor1+valor2+valor3;
        int grados1=valor1*360/suma;
        int grados2=valor2*360/suma;
        int grados3=valor3*360/suma;
        g.setColor(new Color(225,0,0));
        g.fillArc(50, 250, 200, 200, 0, grados1);
        g.fillRect(370, 250, 20, 20);
        g.drawString("Partido 1", 400, 270);
    
        g.setColor(new Color(0,128,0));
        g.fillArc(50, 250, 200, 200, grados1, grados2);
        g.fillRect(370, 280, 20, 20);
        g.drawString("Partido 2", 400, 300);
    
        g.setColor(new Color(0,0,255));
        g.fillArc(50, 250, 200, 200, grados1+grados2,grados3);
        g.fillRect(370, 310, 20, 20);
        g.drawString("Partido 3", 400, 330);
    
    }
    }
    private int retornarMayor(int v1,int v2,int v3){
        if(v1>v2&&v1>v3){
            return v1;   
        }else{
            if(v2>v3){
                return v2;
            }else{
                if(v3>v1&&v3>v2){
                    return v3;
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblPartido1;
    private javax.swing.JButton btnGraficos;
    private javax.swing.JLabel lblPartido2;
    private javax.swing.JLabel lblpartido3;
    private javax.swing.JTextField txtPartido1;
    private javax.swing.JTextField txtPartido2;
    private javax.swing.JTextField txtPartido3;
    // End of variables declaration//GEN-END:variables
}
